import * as T from 'three';
import { Reflector } from 'three/addons/objects/Reflector.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { clone as cloneSkinned } from 'three/addons/utils/SkeletonUtils.js';
import {createModelLoader} from './model-loader.mjs';
import { conversationClip } from './conversation-animation.mjs';
import { skyEnvironment } from '/corporate-showdown/studio-materials.mjs';
import { buildOffice, buildCoast } from '/corporate-showdown/studio-scene.mjs';
import { ROOMS, APPEARANCES, STATIONS, EVENT_SPACE, CENTRAL_LOUNGE } from '/corporate-showdown/shared/office-design.mjs';
import { ROOM_ENTRIES, validFloorPosition } from '/corporate-showdown/shared/headquarters-layout.mjs';
const $=id=>document.getElementById(id), scene=new T.Scene();scene.background=new T.Color(0xb9d9e5);scene.fog=new T.Fog(0xcde3e7,220,800);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.info.autoReset=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;$('viewport').append(renderer.domElement);
const camera=new T.PerspectiveCamera(55,innerWidth/innerHeight,.08,800),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=115;controls.minDistance=5;controls.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xdaf3ff,0xc2b49a,.65));const sun=new T.DirectionalLight(0xffefcc,2);sun.position.set(-30,45,-30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-48,right:48,top:48,bottom:-48,near:1,far:130});sun.shadow.bias=-.0003;scene.add(sun);
scene.environment=skyEnvironment(renderer);scene.environmentIntensity=.32;const office=buildOffice();
// Batch static geometry by material for efficient browsing, preserving named source nodes for GLB export.
function batchModel(source,exclude=()=>false){source.updateMatrixWorld(true);const batches=new Map();source.traverse(m=>{if(!m.isMesh||exclude(m))return;const g=(m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone()).applyMatrix4(m.matrixWorld);if(!batches.has(m.material))batches.set(m.material,[]);batches.get(m.material).push(g);});const result=new T.Group();for(const [material,geometries]of batches){const mesh=new T.Mesh(mergeGeometries(geometries),material);mesh.castShadow=!material.transparent;mesh.receiveShadow=!material.transparent;result.add(mesh);for(const g of geometries)g.dispose();}return result;}
const visual=batchModel(office.root,m=>{if(m.name.startsWith('Corridor_Mirror_'))return true;for(let p=m;p;p=p.parent)if(p===office.ceiling)return true;return false;});
const coast=buildCoast(),coastVisual=batchModel(coast);const roofVisual=office.ceiling.clone();scene.add(visual,roofVisual,coastVisual);
const mirrors=[];
for(const side of[-1,1]){const mirror=new Reflector(new T.PlaneGeometry(3.2,1.3),{textureWidth:512,textureHeight:512,color:0xf0f0f0,clipBias:.003,multisample:0});mirror.position.set(side*1.407,1.8,12.2);mirror.rotation.y=side===-1?Math.PI/2:-Math.PI/2;scene.add(mirror);mirrors.push(mirror);}
// Opposing corridor mirrors share a bounded reflection pass, avoiding recursive rendering.
for(const mirror of mirrors){const reflect=mirror.onBeforeRender;mirror.onBeforeRender=function(...args){const other=mirrors.find(m=>m!==mirror),wasVisible=other.visible;other.visible=false;try{reflect.apply(this,args);}finally{other.visible=wasVisible;}};}


for(const r of ROOMS){const light=new T.PointLight(0xffefd0,12,12,2);light.position.set(r.x,3.2,r.z);scene.add(light);}
let nativeEnvironment=null,nativeRoof=[],nativeRoofVisual=null;
let mode='overview',yaw=0,pitch=0,last=performance.now(),drag=null,avatar=null;const keys=new Set(), imported=new Map(), mixers=new Map();
function overview(){mode='overview';document.exitPointerLock?.();document.body.classList.remove('walking');controls.enabled=true;camera.fov=55;camera.updateProjectionMatrix();camera.position.set(-48,47,-49);controls.target.set(-2,0,2);office.ceiling.visible=false;updateRoof();$('status').textContent='海岸总部 · Blender 场景 v0.8 · 52 工位';}
function updateRoof(){roofVisual.visible=!nativeEnvironment&&office.ceiling.visible;if(nativeRoofVisual)nativeRoofVisual.visible=office.ceiling.visible;$('roof').textContent=office.ceiling.visible?'隐藏天花板':'显示天花板';}
function enterAt(x,z,heading=Math.PI){mode='walk';document.body.classList.add('walking');controls.enabled=false;camera.fov=74;camera.updateProjectionMatrix();camera.position.set(x,1.68,z);yaw=heading;pitch=0;office.ceiling.visible=true;updateRoof();$('status').textContent='漫游中 · 点击场景锁定鼠标 · Esc 返回鸟瞰';renderer.domElement.requestPointerLock?.();}
$('overview').onclick=overview;$('walk').onclick=()=>enterAt(-20,-18);$('roof').onclick=()=>{office.ceiling.visible=!office.ceiling.visible;updateRoof();};
for(const r of ROOMS){const option=document.createElement('option');option.value=r.id;option.textContent=r.label;$('room').append(option);}
$('room').onchange=()=>{const p=ROOM_ENTRIES[$('room').value];if(p)enterAt(p.x,p.z,p.yaw);else if($('room').value==='elevator')enterAt(0,0);else if($('room').value==='corridor')enterAt(0,5);else if($('room').value==='central-lounge')enterAt(CENTRAL_LOUNGE.entry.x,CENTRAL_LOUNGE.entry.z);else if($('room').value==='lounge')enterAt(-20,7);else if($('room').value==='work')enterAt(-20,-18);$('room').value='';};
$('concept').onclick=()=>$('image').showModal();$('close').onclick=()=>$('image').close();$('image').addEventListener('click',e=>{if(e.target===$('image'))$('image').close();});
addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;keys.add(e.code);if(e.code==='Escape')overview();if(mode==='walk'&&['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());
renderer.domElement.addEventListener('pointerdown',e=>{if(mode==='walk'){drag={x:e.clientX,y:e.clientY};renderer.domElement.requestPointerLock?.();}});addEventListener('pointerup',()=>drag=null);addEventListener('mousemove',e=>{if(mode!=='walk')return;let dx=0,dy=0;if(document.pointerLockElement===renderer.domElement){dx=e.movementX;dy=e.movementY;}else if(drag){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};}yaw-=dx*.0022;pitch=T.MathUtils.clamp(pitch-dy*.0022,-1.3,1.3);});
function canMove(x,z){return validFloorPosition(x,z);}
async function exportBuffer(){// Export hidden ceiling too; context sea and buildings stay separate from the office asset.
  const show=office.ceiling.visible;office.ceiling.visible=true;try{const source=new T.Group();source.name='Coastal_Headquarters_Complete_Environment';if(nativeEnvironment){const model=cloneSkinned(nativeEnvironment);model.traverse(o=>{if(o.userData.is_ceiling)o.visible=true;});source.add(model);}else source.add(office.root.clone(),coast.clone());if(avatar)source.add(cloneSkinned(avatar));return await new GLTFExporter().parseAsync(source,{binary:true,onlyVisible:false});}finally{office.ceiling.visible=show;}}
$('export').onclick=async()=>{const b=$('export');b.disabled=true;b.textContent='正在生成模型…';try{const data=await exportBuffer(),url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='coastal-headquarters-layout.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('status').textContent=`模型已导出 · ${(data.byteLength/1048576).toFixed(1)} MB · 可用 Blender 编辑`;}catch(e){$('status').textContent=`导出失败：${e.message}`;}finally{b.disabled=false;b.textContent='下载 3D 模型 .GLB';}};
for(const job of APPEARANCES.jobs){const o=document.createElement('option');o.value=job.id;o.textContent=job.label;$('job').append(o);}
const professionLabels={female_doctor:'林医生 · 女医生服装样本 · 白大褂 / 听诊器 / 胸牌',female_teacher:'许老师 · 女教师服装样本 · 浅色上装 / 深色裙装 / 细框眼镜'};
let professionPreview=new URLSearchParams(location.search).get('character');
if(!Object.hasOwn(professionLabels,professionPreview))professionPreview=null;
if(professionPreview)$('gender').value='female';
const slot=()=>professionPreview??`${$('gender').value}_${$('job').value}`;
const loader=createModelLoader(),pending=new Map(),avatarClips=new WeakMap();
const conversationReady=loader.loadAsync('/corporate-showdown/assets/animations/conversation-v1/workplace-conversation.glb');
async function prepareAvatar(result,selected){const bank=await conversationReady;const model=result.scene,bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3());if(!Number.isFinite(size.y)||size.y<.01)throw new Error('模型没有有效的人物尺寸');const targetHeight=selected.startsWith('female')?1.68:1.78;model.scale.multiplyScalar(targetHeight/size.y);bounds.setFromObject(model);const center=bounds.getCenter(new T.Vector3());model.position.set(-20-center.x,-bounds.min.y,7-center.z);model.name=`Human_${selected}`;model.userData.appearance=selected;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});const old=imported.get(selected);if(old){scene.remove(old);mixers.delete(old);}imported.set(selected,model);const clips=[...result.animations];if(bank.animations[0].tracks.filter(t=>t.name.endsWith('.quaternion')).every(t=>model.getObjectByName(T.PropertyBinding.parseTrackName(t.name).nodeName)))for(const [name,profession]of [['Explain','老师'],['Listen','诗人'],['Comfort','医生']]){const clip=conversationClip(bank,model,selected,profession);clip.name=selected+'_'+name;clips.push(clip);}avatarClips.set(model,clips);if(clips.length){const mixer=new T.AnimationMixer(model);mixers.set(model,mixer);}return model;}
async function selectAvatar(){const selected=slot();if(avatar)scene.remove(avatar);avatar=imported.get(selected)??null;if(avatar){scene.add(avatar);$('avatar').textContent=professionLabels[selected]??`${$('gender').value==='female'?'女生':'男生'} · ${$('job').selectedOptions[0].textContent} · 骨骼与服装已加载`;$('avatar').dataset.asset=selected;setAvatarAnimation();return;}delete $('avatar').dataset.asset;$('avatar').textContent='正在加载人物与服装…';try{if(!pending.has(selected))pending.set(selected,loader.loadAsync(`/corporate-showdown/assets/characters/${selected}.glb`).then(r=>prepareAvatar(r,selected)).catch(e=>{pending.delete(selected);throw e;}));await pending.get(selected);if(slot()===selected)return selectAvatar();}catch(e){if(slot()===selected)$('avatar').textContent=`人物加载失败：${e.message}`;}}
$('gender').onchange=$('job').onchange=()=>{professionPreview=null;selectAvatar();};
$('doctor-preview').onclick=async()=>{professionPreview='female_doctor';$('gender').value='female';await selectAvatar();focusAvatar();};
$('teacher-preview').onclick=async()=>{professionPreview='female_teacher';$('gender').value='female';await selectAvatar();focusAvatar();};
$('human').onchange=async()=>{const file=$('human').files[0];if(!file)return;const selected=slot();$('avatar').textContent='读取模型…';try{await prepareAvatar(await loader.parseAsync(await file.arrayBuffer(),''),selected);if(slot()===selected)return selectAvatar();}catch(e){$('avatar').textContent=`导入失败：${e.message}`;}};
function setAvatarAnimation(){if(!avatar)return;const mixer=mixers.get(avatar),clips=avatarClips.get(avatar)??[],name=$('preview-animation').value,clip=clips.find(c=>c.name===slot()+'_'+name)??clips.find(c=>/idle/i.test(c.name))??clips[0];if(!mixer||!clip)return;mixer.stopAllAction();const action=mixer.clipAction(clip),once=['Attack','Hit','Down','Cast'].includes(name);action.setLoop(once?T.LoopOnce:T.LoopRepeat,once?1:Infinity);action.clampWhenFinished=once;action.reset().play();$('avatar').dataset.animation=clip.name;}
$('preview-animation').onchange=setAvatarAnimation;
function focusAvatar(){overview();camera.position.set(-20,1.75,10.7);controls.target.set(-20,.95,7);controls.minDistance=1.5;controls.update();$('status').textContent=professionPreview?'职业样本近览 · 服装试作，脸部与动作继续精修':'人物近览 · 男女与职务选择可切换服装';}
$('focus-avatar').onclick=focusAvatar;
async function loadNativeEnvironment(){try{const result=await loader.loadAsync('/corporate-showdown/assets/models/coastal-headquarters-complete.glb');nativeEnvironment=result.scene;nativeEnvironment.name='Blender_Headquarters_v08';nativeEnvironment.traverse(o=>{if(o.userData.is_ceiling)nativeRoof.push(o);if(o.isMesh){o.castShadow=!o.material?.transparent;o.receiveShadow=true;}if(o.name.startsWith('Corridor_Mirror_'))o.visible=false;});const staticVisual=batchModel(nativeEnvironment,m=>m.isSkinnedMesh||m.userData.environment_character||m.userData.is_ceiling||m.material?.name?.includes('Mirror'));nativeRoofVisual=batchModel(nativeEnvironment,m=>!m.userData.is_ceiling);nativeEnvironment.traverse(o=>{if(o.isMesh&&!o.userData.environment_character)o.visible=false;});scene.remove(visual,roofVisual,coastVisual);scene.add(staticVisual,nativeRoofVisual,nativeEnvironment);updateRoof();$('status').textContent='Blender 完整场景已加载 · 8 套职场人物 · 52 工位';}catch(e){$('status').textContent=`Blender 场景加载失败：${e.message}`;}}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function frame(t){const dt=Math.min((t-last)/1000,.05);last=t;if(mode==='overview')controls.update();else{camera.rotation.order='YXZ';camera.position.y=1.68+office.floorHeight(camera.position.x,camera.position.z);camera.rotation.set(pitch,yaw,0);let f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),r=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),len=Math.hypot(f,r)||1,speed=(keys.has('ShiftLeft')?5:2.8)*dt;let dx=(-Math.sin(yaw)*f+Math.cos(yaw)*r)/len*speed,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*r)/len*speed;if(canMove(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(canMove(camera.position.x,camera.position.z+dz))camera.position.z+=dz;}for(const [model,mixer]of mixers)if(model===avatar)mixer.update(dt);renderer.info.reset();renderer.render(scene,camera);requestAnimationFrame(frame);}
overview();selectAvatar().then(()=>{if(professionPreview)focusAvatar();});loadNativeEnvironment();requestAnimationFrame(frame);
// Read-only diagnostics and an export method support model validation without a server write endpoint.
window.officeStudio={scene,camera,office,stations:STATIONS,rooms:ROOMS,exportBuffer,get nativeEnvironment(){return nativeEnvironment;},get avatar(){return avatar;},get avatarSlots(){return [...imported.keys()];},get mode(){return mode;},get rendererInfo(){return renderer.info;}};
