import test from 'node:test';import assert from 'node:assert/strict';
import {createRoom,addPlayer,setReady,startRoom,stepRoom,focusNpc,talkToNpc,snapshot,validPosition} from '../simulation.mjs';
import {LEVEL} from '../shared/level.mjs';import {NPC_ROUTINES,nextClueHint} from '../shared/story.mjs';import {SnapshotInterpolation} from '../public/network-state.mjs';
function setup(){const room=createRoom('ROUTINE','single'),player=addPlayer(room,'p','员工');setReady(room,player,true,room.loadoutRevision,LEVEL.revision,LEVEL.characterRevision);assert.ok(startRoom(room));return {room,player};}
function advance(room,seconds){for(let i=0;i<seconds*30;i++)stepRoom(room,1/30);}
test('all professional NPCs cycle through real reachable stations without leaving collision bounds',()=>{const {room}=setup();const moving=new Set();for(const n of room.npcs)for(const point of NPC_ROUTINES[n.id])assert.ok(validPosition(point.x,point.z,.4));for(let i=0;i<240*30;i++){stepRoom(room,1/30);for(const n of room.npcs){assert.ok(validPosition(n.x,n.z,.36),n.id);if(n.behavior==='walking')moving.add(n.id);}}assert.equal(moving.size,6);for(const n of room.npcs)assert.ok(n.visits>=2,n.id+' visits '+n.visits);assert.equal(room.story.clues.length,0);assert.equal(room.story.phase,'explore');assert.equal(snapshot(room).npcs[0].navPath,undefined);});
test('authoritative conversation pauses and faces the player, releases on end, distance, timeout and disconnect',()=>{for(const stop of ['end','distance','timeout','disconnect']){const {room,player}=setup(),n=room.npcs[0];player.x=n.x+.8;player.z=n.z;focusNpc(room,player,n.id);const before={x:n.x,z:n.z};advance(room,22);assert.equal(n.behavior,'talking');assert.equal(n.x,before.x);assert.equal(n.z,before.z);assert.equal(n.fx,1);assert.equal(snapshot(room).npcs[0].conversing,true);if(stop==='end')focusNpc(room,player,null,false);if(stop==='distance')player.x=-16;if(stop==='timeout')advance(room,24);if(stop==='disconnect')player.connected=false;advance(room,1);assert.equal(n.conversation,null,stop);assert.notEqual(n.behavior,'talking',stop);assert.ok(Math.hypot(n.x-before.x,n.z-before.z)>.1,stop);}});
test('invalid conversation never freezes NPCs or grants information; working NPCs yield to players and conflicts',()=>{const {room,player}=setup(),teacher=room.npcs[0];assert.throws(()=>focusNpc(room,player,'finance'),/靠近/);assert.throws(()=>focusNpc(room,player,'missing'),/靠近/);assert.equal(room.npcs.every(n=>!n.conversation),true);player.state='down';assert.throws(()=>focusNpc(room,player,'teacher'));player.state='active';advance(room,20.1);player.x=teacher.x;player.z=teacher.z+.3;advance(room,.1);assert.equal(teacher.behavior,'waiting');assert.equal(teacher.activity,'等通道让开');player.x=-18;room.enemies=[{id:'dummy',kind:'runner',hp:100,x:teacher.x,z:teacher.z,stunUntil:999}];advance(room,.1);assert.equal(teacher.activity,'避让冲突，暂停手头工作');assert.equal(room.story.clues.length,0);});
test('contextual clue advice reflects actual progress and NPC snapshots interpolate movement',()=>{const {room,player}=setup();assert.match(nextClueHint(room.story),/许老师/);player.x=-20;player.z=5.8;talkToNpc(room,player,'teacher','where');assert.match(room.story.dialogue.text,/我这里有原始日程/);talkToNpc(room,player,'teacher','schedule');assert.match(nextClueHint(room.story),/顾律师/);const a=snapshot(room);advance(room,.2);const b=snapshot(room);a.npcs[0].x=-20;b.npcs[0].x=-19.8;const interp=new SnapshotInterpolation();interp.push(a,0);interp.push(b,200);const n=interp.entities(200).get('teacher');assert.ok(n.x>-20&&n.x<-19.8);assert.equal(n.profession,'老师');});
