import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,copyFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';
import {Box3,PerspectiveCamera,Group,Vector3} from 'three';import {createModelLoader} from '../public/model-loader.mjs';import {FirstPersonArms} from '../public/first-person-arms.mjs';import {optimizePagesAssets} from '../tools/optimize-pages-assets.mjs';
async function meshOnly(file){const b=await readFile(file),length=b.readUInt32LE(12),doc=JSON.parse(b.toString('utf8',20,20+length));for(const mesh of doc.meshes??[])for(const p of mesh.primitives)delete p.material;delete doc.images;delete doc.textures;delete doc.materials;const text=Buffer.from(JSON.stringify(doc)),body=Buffer.concat([text,Buffer.alloc((4-text.length%4)%4,32)]),bin=b.subarray(20+length),head=Buffer.alloc(20);head.writeUInt32LE(0x46546c67,0);head.writeUInt32LE(2,4);head.writeUInt32LE(20+body.length+bin.length,8);head.writeUInt32LE(body.length,12);head.writeUInt32LE(0x4e4f534a,16);const bytes=Buffer.concat([head,body,bin]);return createModelLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');}
test('web compression decodes with shipped decoder, preserves animated rigs and deformed bounds, and fits actual arm wrist',{timeout:120000},async t=>{
 const out=await mkdtemp(join(tmpdir(),'showdown-compressed-'));t.after(()=>rm(out,{recursive:true,force:true}));
 const files=[['assets/characters/weapon-ready-v1/male_programmer.glb','assets/characters/male_programmer.glb'],['assets/characters/first-person-v1/female_sales.glb','assets/characters/first-person/female_sales.glb']];
 const inventory=[];for(const [source,path]of files){await mkdir(dirname(join(out,path)),{recursive:true});await copyFile(source,join(out,path));inventory.push({path,bytes:(await readFile(source)).length});}
 const report=await optimizePagesAssets(out,inventory);assert.equal(report.models.length,2);
 for(const [source,path]of files){const raw=await meshOnly(source),optimized=await meshOnly(join(out,path));assert.deepEqual(optimized.animations.map(a=>a.name).sort(),raw.animations.map(a=>a.name).sort());raw.scene.updateMatrixWorld(true);optimized.scene.updateMatrixWorld(true);const a=new Box3().setFromObject(raw.scene,true),b=new Box3().setFromObject(optimized.scene,true);assert.ok(a.min.distanceTo(b.min)<.006&&a.max.distanceTo(b.max)<.006,path+' deformed bounds changed');assert.ok(inventory.find(i=>i.path===path).bytes<(await readFile(source)).length*.5);
  optimized.scene.traverse(node=>{if(!node.geometry?.attributes.position)return;const g=node.geometry,position=g.attributes.position;assert.ok(position.array instanceof Float32Array);const baked=g.clone().applyMatrix4(node.matrixWorld);for(const i of [0,Math.floor(position.count/2),position.count-1])assert.ok(new Vector3().fromBufferAttribute(position,i).applyMatrix4(node.matrixWorld).distanceTo(new Vector3().fromBufferAttribute(baked.attributes.position,i))<1e-5,'CPU batching overflow');baked.dispose();});
  if(path.includes('first-person')){const camera=new PerspectiveCamera(),arms=new FirstPersonArms(camera,new Map([['female_sales',optimized]]),()=>new Group(),()=>{});arms.sync({state:'active',weapon:'pistol',attackUntil:0},'female_sales',1,.016,true);camera.updateMatrixWorld(true);assert.ok(camera.worldToLocal(arms.actor.hand.getWorldPosition(new Vector3())).distanceTo(new Vector3(.13,-.28,-.5))<1e-5);arms.clear();}
 }
});
