import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {WebSocket} from 'ws';import {randomUUID} from 'node:crypto';import {GameSession} from '../client/session.mjs';
async function wait(fn){const end=performance.now()+7000;while(performance.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,15));}throw Error('story session timed out');}
test('real single-player room rejects another player and validates/idempotently grants nearby NPC information',{timeout:15000},async t=>{
 const server=spawn(process.execPath,['prototype/server.mjs'],{env:{...process.env,PORT:'0',HOST:'127.0.0.1'},stdio:['ignore','pipe','pipe']});t.after(()=>server.kill());const url=await new Promise((resolve,reject)=>{server.stdout.on('data',s=>{const m=String(s).match(/http:\/\/127\.0\.0\.1:\d+/);if(m)resolve(m[0]);});server.once('error',reject);});
 const controlsModule=await fetch(url+'/input-controls.mjs');assert.equal(controlsModule.status,200);assert.match(controlsModule.headers.get('content-type'),/javascript/);
 for(const name of ['story','camera-rig','weapons','weapon-geometry','weapon-grip','character-assets']){const response=await fetch(url+'/shared/'+name+'.mjs');assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/javascript/);}
 for(const name of ['first-person-arms','character-animation']){const response=await fetch(url+'/'+name+'.mjs');assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/javascript/);}
 for(const slot of ['male_programmer','female_programmer']){const response=await fetch(url+'/assets/characters/first-person/'+slot+'.glb');assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/model\/gltf-binary/);assert.equal(Buffer.from(await response.arrayBuffer()).toString('ascii',0,4),'glTF');}
 const doctorAsset=await fetch(url+'/assets/characters/female_doctor.glb');assert.equal(doctorAsset.status,200);assert.match(doctorAsset.headers.get('content-type'),/model\/gltf-binary/);assert.equal(Buffer.from(await doctorAsset.arrayBuffer()).toString('ascii',0,4),'glTF');
 const teacherAsset=await fetch(url+'/assets/characters/female_teacher.glb');assert.equal(teacherAsset.status,200);assert.match(teacherAsset.headers.get('content-type'),/model\/gltf-binary/);assert.equal(Buffer.from(await teacherAsset.arrayBuffer()).toString('ascii',0,4),'glTF');
 const salesAsset=await fetch(url+'/assets/characters/male_sales.glb');assert.equal(salesAsset.status,200);const sales=Buffer.from(await salesAsset.arrayBuffer());const salesDoc=JSON.parse(sales.toString('utf8',20,20+sales.readUInt32LE(12)));assert.equal(salesDoc.materials.find(m=>m.name.includes('high-poly')).alphaMode,'MASK');
 const sent=[],messages=[];const clients=[0,1].map(i=>new GameSession({openSocket:()=>{const socket=new WebSocket(url.replace('http:','ws:')+'/socket');const original=socket.send.bind(socket);socket.send=value=>{if(i===0)sent.push(JSON.parse(value));original(value);};return socket;},requestId:randomUUID,onMessage:message=>messages.push(message)}));t.after(()=>clients.forEach(c=>c.dispose()));const timer=setInterval(()=>clients.forEach(c=>c.tick()),30);t.after(()=>clearInterval(timer));clients.forEach(c=>c.connect());await wait(()=>clients.every(c=>c.connected));const c=clients[0];c.send({type:'create',mode:'single'});await wait(()=>c.state?.status==='lobby');assert.equal(c.state.mode,'single');clients[1].send({type:'join',code:c.state.id});await wait(()=>messages.some(m=>/已满/.test(m)));assert.equal(c.state.players.length,1);
 c.ready();await wait(()=>c.state.players[0].ready);c.command({type:'start'});await wait(()=>c.state.status==='running');assert.equal(c.state.enemies.length,0);
 c.command({type:'dialogue',npcId:'finance',topicId:'ledger'});await wait(()=>messages.some(m=>/靠近/.test(m)));assert.equal(c.state.story.clues.length,0);
 c.command({type:'conversation',npcId:'teacher',active:true});await wait(()=>c.state.npcs.find(n=>n.id==='teacher').conversing);const conversation=sent.find(d=>d.type==='conversation');c.send(conversation);await new Promise(r=>setTimeout(r,100));assert.equal(c.state.npcs.filter(n=>n.conversing).length,1);assert.equal(c.state.story.clues.length,0);c.command({type:'conversation',active:false});await wait(()=>!c.state.npcs.some(n=>n.conversing));
 c.command({type:'dialogue',npcId:'teacher',topicId:'schedule'});await wait(()=>c.state.story.clues.includes('schedule'));const command=sent.find(d=>d.type==='dialogue'&&d.npcId==='teacher');c.send(command);await new Promise(r=>setTimeout(r,160));assert.deepEqual(c.state.story.clues,['schedule']);assert.equal(c.state.story.choices.filter(k=>k==='teacher:schedule').length,1);assert.equal(c.state.story.dialogue.name,'许老师');c.input({x:0,z:0,aimX:0,aimZ:-1,pickup:true});await wait(()=>c.state.players[0].weapon==='pistol');assert.equal(c.state.players[0].inventory[0].ammo,12);
 c.input({x:0,z:0,aimX:1,aimZ:0,attack:true});await wait(()=>c.state.players[0].inventory[0].ammo===11);const fired=sent.filter(d=>d.type==='input').at(-1);c.send({...fired,ammo:999,damage:999});await new Promise(r=>setTimeout(r,180));assert.equal(c.state.players[0].inventory[0].ammo,11);
 c.input({x:0,z:0,reload:true});await wait(()=>c.state.players[0].reloadUntil>c.state.elapsed);await wait(()=>c.state.players[0].inventory[0].ammo===12);assert.equal(c.state.players[0].inventory[0].reserve,47);c.leave();assert.equal(c.state,null);
});
