import {AudioClip,AudioSource,Node,resources,sys} from 'cc';
import {AudioCues} from './canonical/client/audio-cues.js';
import {loadAudioSettings,saveAudioSettings,normalizeAudioSettings} from './canonical/public/audio-settings.js';
type Slot={source:AudioSource;channel:string;until:number};
export class EngineAudio {
 settings:any;private cues=new AudioCues();private clips=new Map<string,AudioClip>();private slots:Slot[]=[];private root:Node;private music:AudioSource;private ambient:AudioSource;private preparing:Promise<void>|null=null;private disposed=false;private hidden=false;private active=false;private pulse='';private duckUntil=0;private captionUntil=0;private priorityUntil=0;private cooldowns=new Map<string,number>();private storage:any;
 diagnostics(){return {clips:this.clips.size,active:this.active,hidden:this.hidden,musicPlaying:this.music.playing,ambientPlaying:this.ambient.playing,voices:this.slots.filter(s=>s.source.playing).length,settings:this.settings,caption:this.caption,status:this.status};}
 caption='';status='声音资源未准备';
 constructor(parent:Node){try{this.storage=sys.localStorage;}catch{}this.settings=loadAudioSettings(this.storage);this.root=new Node('Office audio');parent.addChild(this.root);const source=(name:string)=>{const n=new Node(name);this.root.addChild(n);const a=n.addComponent(AudioSource);a.playOnAwake=false;return a;};this.music=source('Countdown');this.ambient=source('Office ambience');for(let i=0;i<12;i++)this.slots.push({source:source('Cue '+i),channel:'effects',until:0});}
 prepare(){if(this.preparing)return this.preparing;this.preparing=Promise.all(['shot','reload','empty','ambient','step','hit','skill','danger','notice','pulse_108','pulse_132','pulse_158','pulse_184'].map(name=>new Promise<void>((resolve,reject)=>{if(this.clips.has(name)){resolve();return;}resources.load('audio/'+name,AudioClip,(error,clip)=>{if(error){reject(error);return;}if(!this.disposed){clip.addRef();this.clips.set(name,clip);}resolve();});}))).then(()=>{this.status='声音资源已准备';}).catch(error=>{this.preparing=null;this.status='声音加载失败';throw error;});return this.preparing;}
 configure(patch:any){this.settings=normalizeAudioSettings({...this.settings,...patch});saveAudioSettings(this.storage,this.settings);if(!this.settings.captions)this.caption='';if(!this.settings.enabled)this.silence();this.volume(performance.now()/1000);}
 tick(state:any,player:any){const now=performance.now()/1000;this.active=Boolean(state?.status==='running');if(!this.active){this.stop();return;}if(this.hidden){this.silence();this.caption='';return;}const cues=this.cues.update(state,player,now);for(const cue of cues)this.play(cue,now);if(now>this.captionUntil)this.caption='';this.volume(now);if(this.settings.enabled&&this.clips.has('ambient')&&!this.ambient.playing){this.ambient.clip=this.clips.get('ambient')!;this.ambient.loop=true;this.ambient.play();}if(this.settings.enabled&&this.pulse&&!this.music.playing){this.music.clip=this.clips.get(this.pulse)!;this.music.loop=true;this.music.play();}}
 event(event:any){const now=performance.now()/1000;for(const cue of this.cues.event(event))this.play(cue,now);}
 private play(cue:any,now:number){if(cue.stop){this.stop();return;}if(!this.active||this.hidden)return;if(cue.text&&this.settings.captions&&(cue.priority==='danger'||now>=this.priorityUntil)){this.caption=cue.text;this.captionUntil=now+(cue.priority==='danger'?3:4);if(cue.priority==='danger')this.priorityUntil=now+3;}if(cue.channel==='alerts'||cue.channel==='voice')this.duckUntil=Math.max(this.duckUntil,now+(cue.channel==='voice'?3:1.2));if(cue.loop){if(this.pulse!==cue.name){this.music.stop();this.pulse=cue.name;}return;}if(!this.settings.enabled||!this.clips.has(cue.name)||now<(this.cooldowns.get(cue.name)??0))return;this.cooldowns.set(cue.name,now+(({step:.2,hit:.08,skill:.25,danger:.5} as Record<string,number>)[cue.name]??.1));if(this.slots.filter(s=>s.channel===cue.channel&&s.until>now).length>=(cue.channel==='effects'?8:4))return;const slot=this.slots.find(s=>s.until<=now);if(!slot)return;slot.source.stop();slot.source.clip=this.clips.get(cue.name)!;slot.channel=cue.channel;slot.until=now+.5;this.volume(now);slot.source.play();}
 private volume(now:number){const master=this.active&&!this.hidden&&this.settings.enabled?this.settings.master:0;const duck=now<this.duckUntil ? .22 : 1;this.music.volume=master*this.settings.music*.45*duck;this.ambient.volume=master*this.settings.ambient*.04*duck;for(const slot of this.slots)slot.source.volume=master*this.settings[slot.channel]*.65;}
 private silence(){this.music.stop();this.ambient.stop();for(const slot of this.slots){slot.source.stop();slot.until=0;}}
 setHidden(hidden:boolean){this.hidden=hidden;if(hidden){this.silence();this.caption='';}}
 stop(){this.active=false;this.silence();this.cues.reset();this.pulse='';this.caption='';this.cooldowns.clear();this.duckUntil=this.priorityUntil=0;}
 dispose(){this.disposed=true;this.stop();this.root.destroy();for(const clip of Array.from(this.clips.values()))clip.decRef();this.clips.clear();}
}
