import {SkeletalAnimation,Node,Mesh,MeshRenderer,Material,Color,primitives,utils,Vec3,Quat} from 'cc';
import {weaponParts} from './canonical/shared/weapon-geometry.js';
import {weaponGrip} from './canonical/shared/weapon-grip.js';
import {WEAPONS} from './canonical/shared/weapons.js';
import {floorHeight} from './canonical/shared/level.js';
type Entry={node:Node;kind:string;meshes:Mesh[]};
// Shared original part definitions; meshes merge by color to bound weapon draw calls.
export class EngineWeapons{
 private firstPerson:{socket:Node;basis:Quat;path:string}|null=null;
 private sockets=new Map<Node,{node:Node;animation:SkeletalAnimation;path:string}>();
 private entries=new Map<string,Entry>();private materials=new Map<string,Material>();private flashes:{entry:Entry;until:number}[]=[];private eventId=0;
 constructor(private root:Node,private camera:Node){}
 private material(color:string,unlit=false){const key=color+unlit;if(!this.materials.has(key)){const m=new Material();m.initialize({effectName:unlit?'builtin-unlit':'builtin-standard'});const c=new Color();Color.fromHEX(c,color);m.setProperty('mainColor',c);if(!unlit){m.setProperty('roughness',.55);m.setProperty('metallic',.35);}this.materials.set(key,m);}return this.materials.get(key)!;}
 private create(kind:string):Entry{const node=new Node(WEAPONS[kind].name),groups=new Map<string,{positions:number[];normals:number[];uvs:number[];indices:number[]}>();
  for(const p of weaponParts(WEAPONS[kind].family)){const g=p.shape==='box'?primitives.box({width:p.size![0],height:p.size![1],length:p.size![2]}):primitives.cylinder(p.r!,p.r!,p.length!,{radialSegments:12});const b=groups.get(p.color)??{positions:[],normals:[],uvs:[],indices:[]};groups.set(p.color,b);const offset=b.positions.length/3;const angle=p.shape==='box'?(p.tilt??0)*Math.PI/180:p.axis==='x'?Math.PI/2:0;
   const rotate=(x:number,y:number,z:number)=>p.axis==='z'?[x,-z,y]:[x*Math.cos(angle)-y*Math.sin(angle),x*Math.sin(angle)+y*Math.cos(angle),z];
   for(let i=0;i<g.positions.length;i+=3){const v=rotate(g.positions[i],g.positions[i+1],g.positions[i+2]);b.positions.push(v[0]+p.pos[0],v[1]+p.pos[1],v[2]+p.pos[2]);const n=rotate(g.normals![i],g.normals![i+1],g.normals![i+2]);b.normals.push(...n);}b.uvs.push(...g.uvs!);b.indices.push(...g.indices!.map(i=>i+offset));
  }
  const meshes:Mesh[]=[];for(const [color,g]of groups){const part=new Node('武器材质 '+color);node.addChild(part);const renderer=part.addComponent(MeshRenderer),mesh=utils.createMesh(g);renderer.mesh=mesh;renderer.setMaterial(this.material(color),0);meshes.push(mesh);}return {node,kind,meshes};
 }
 private release(e:Entry){for(const mesh of e.meshes)mesh.destroy();if(e.node.isValid)e.node.destroy();}
 private handSocket(actor:Node){let cached=this.sockets.get(actor);if(cached?.node.isValid)return cached.node;const animation=actor.getComponent(SkeletalAnimation)??actor.getComponentInChildren(SkeletalAnimation);if(!animation)throw Error('人物缺少骨骼动画');const find=(n:Node):Node|null=>{if(n.name==='hand_r')return n;for(const child of n.children){const found=find(child);if(found)return found;}return null;};const hand=find(animation.node);if(!hand)throw Error('人物缺少右手握持骨骼');const path:string[]=[];let joint:Node|null=hand;while(joint&&joint!==animation.node){path.unshift(joint.name);joint=joint.parent;}if(joint!==animation.node)throw Error('握持骨骼不在动画根节点');const node=new Node('右手武器挂点');animation.node.addChild(node);animation.sockets=[...animation.sockets,new SkeletalAnimation.Socket(path.join('/'),node)];this.sockets.set(actor,{node,animation,path:path.join('/')});return node;}
 sync(state:any,playerId:string,thirdPerson:boolean,actors:Map<string,{node:Node}>,firstPerson:{socket:Node;basis:Quat;path:string}|null=null){this.firstPerson=firstPerson;const keep=new Set<string>();const get=(id:string,kind:string,parent:Node)=>{keep.add(id);let e=this.entries.get(id);if(e?.kind!==kind||!e?.node.isValid){if(e)this.release(e);e=this.create(kind);this.entries.set(id,e);}if(e.node.parent!==parent)parent.addChild(e.node);return e.node;};
  if(state.status==='running'){
   for(const i of state.items)if(WEAPONS[i.kind]){const n=get('item:'+i.id,i.kind,this.root);n.setPosition(i.x,floorHeight(i.x,i.z)+.45,i.z);}
   for(const p of state.players)if(WEAPONS[p.weapon]&&p.state==='active'){const first=p.id===playerId&&!thirdPerson,actor=actors.get(p.id)?.node;if(!first&&!actor)continue;const parent=first?(firstPerson?.socket??this.camera):this.handSocket(actor!);const n=get('held:'+p.id,p.weapon,parent);if(first&&firstPerson){const grip=weaponGrip(WEAPONS[p.weapon].family),position=new Vec3(...grip.position as [number,number,number]),rotation=new Quat();Vec3.transformQuat(position,position,firstPerson.basis);Quat.fromEuler(rotation,0,0,grip.rotation[2]*180/Math.PI);Quat.multiply(rotation,firstPerson.basis,rotation);n.setPosition(position);n.setRotation(rotation);}else if(first){n.setPosition(.25,-.22,-.65);n.setRotationFromEuler(0,90,0);}else{const grip=weaponGrip(WEAPONS[p.weapon].family);n.setPosition(...grip.position as [number,number,number]);n.setRotationFromEuler(0,0,grip.rotation[2]*180/Math.PI);}}
  }
  for(const [id,e]of this.entries)if(!keep.has(id)){this.release(e);this.entries.delete(id);}
  for(const actor of this.sockets.keys())if(!actor.isValid)this.sockets.delete(actor);
  const now=performance.now();for(let i=this.flashes.length-1;i>=0;i--)if(now>=this.flashes[i].until){this.release(this.flashes[i].entry);this.flashes.splice(i,1);}
 }
 event(event:any){if(event.id<=this.eventId)return;this.eventId=event.id;if(event.kind!=='shot')return;for(const ray of event.rays??[]){const a=new Vec3(ray.from.x,ray.from.y,ray.from.z),b=new Vec3(ray.to.x,ray.to.y,ray.to.z),length=Vec3.distance(a,b);if(length<.001)continue;const node=new Node('弹道反馈');this.root.addChild(node);const renderer=node.addComponent(MeshRenderer),mesh=utils.createMesh(primitives.box({width:.012,height:.012,length}));renderer.mesh=mesh;renderer.setMaterial(this.material('#ffe1a1',true),0);node.setPosition((a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2);node.lookAt(b);this.flashes.push({entry:{node,kind:'trace',meshes:[mesh]},until:performance.now()+90});}}
 diagnostics(){return Array.from(this.entries).filter(([id])=>id.startsWith('held:')).map(([id,e])=>{const socket=Array.from(this.sockets.values()).find(s=>s.node===e.node.parent);const forward=new Vec3(),up=new Vec3(),cameraForward=new Vec3();Vec3.transformQuat(forward,new Vec3(1,0,0),e.node.worldRotation);Vec3.transformQuat(up,new Vec3(0,1,0),e.node.worldRotation);Vec3.transformQuat(cameraForward,new Vec3(0,0,-1),this.camera.worldRotation);return {forward:{x:forward.x,y:forward.y,z:forward.z},up:{x:up.x,y:up.y,z:up.z},cameraForward:{x:cameraForward.x,y:cameraForward.y,z:cameraForward.z},id,kind:e.kind,parent:e.node.parent?.name,mode:socket?'hand':e.node.parent===this.firstPerson?.socket?'first-hand':'camera',bonePath:socket?.path??(e.node.parent===this.firstPerson?.socket?this.firstPerson?.path:null),active:e.node.activeInHierarchy,world:{x:e.node.worldPosition.x,y:e.node.worldPosition.y,z:e.node.worldPosition.z}};});}
 clear(){this.firstPerson=null;for(const [actor,s]of this.sockets){if(actor.isValid){s.animation.sockets=s.animation.sockets.filter(socket=>socket.target!==s.node);if(s.node.isValid)s.node.destroy();}}this.sockets.clear();for(const e of this.entries.values())this.release(e);this.entries.clear();for(const f of this.flashes)this.release(f.entry);this.flashes=[];this.eventId=0;}
 dispose(){this.clear();for(const m of this.materials.values())m.destroy();this.materials.clear();}
}
