import {_decorator,Component,Prefab,instantiate,SkeletalAnimation,input,Input,KeyCode,EventKeyboard,EventMouse,Vec3,Node,sys,resources,MeshRenderer,Material,Color,utils,primitives,AnimationClip,game,Game,EventTouch,profiler,Camera} from 'cc';
import {EngineUi} from './EngineUi';
import {EngineWeapons} from './EngineWeapons';
import {EngineFirstPerson} from './EngineFirstPerson';
import {WEAPONS,weaponLabel} from './canonical/shared/weapons.js';
import {EngineAudio} from './EngineAudio';
import {EnvironmentBatching} from './EnvironmentBatching';
import {EnvironmentInstancing} from './EnvironmentInstancing';
import {EngineMaterialAlpha} from './EngineMaterialAlpha';
import {EngineCoastalSky} from './EngineCoastalSky';
import {InputControls} from './canonical/client/input-controls.js';
import {INPUT_HZ} from './canonical/shared/protocol.js';
import {GameSession} from './canonical/client/session.js';
import {STORY_NPCS,nearestStoryNpc,storyTopicAvailable} from './canonical/shared/story.js';
import {ConversationFocus,conversationFacing} from './canonical/public/conversation-focus.js';
import {characterAssetSlot} from './canonical/shared/character-assets.js';
import {cameraPose,cameraAvatarVisible} from './canonical/shared/camera-rig.js';
import {WALLS} from './canonical/shared/headquarters-layout.js';
import {LEVEL,floorHeight} from './canonical/shared/level.js';
import {selectAnimation,ANIMATION_NAMES,WEAPON_ANIMATION_NAMES} from './canonical/shared/animation.js';
const {ccclass,property}=_decorator;
type Actor={node:Node;animation:SkeletalAnimation;slot:string;action:string;marker:unknown;position:Vec3;hp:number;hitUntil:number;lensAlpha:number|null};

@ccclass('PlatformProbe')
export class PlatformProbe extends Component {
 @property(Prefab) environment:Prefab|null=null;
 @property(Prefab) character:Prefab|null=null;
 @property serverUrl='ws://127.0.0.1:4173/socket';
 private coastalSky!:EngineCoastalSky;private materialAlpha=new EngineMaterialAlpha();private office:Node|null=null;private environmentBatching:EnvironmentBatching|EnvironmentInstancing|null=null;private arms!:EngineFirstPerson;private weapons!:EngineWeapons;private sound!:EngineAudio;private soundSettings=false;private session!:GameSession;private ui!:EngineUi;private camera!:Node;private escapeHeld=false;private held=new Set<string>();private actors=new Map<string,Actor>();private props=new Map<string,Node>();private prefabs=new Map<string,Prefab>();private loads=new Map<string,Promise<Prefab>>();
 private focus=new ConversationFocus();private dialogueNpc='';private thirdPerson=true;private avatarVisible=true;private cameraDistance=0;private menu=false;private yaw=0;private pitch=0;private controls=new InputControls();private inputTimer:ReturnType<typeof setInterval>|null=null;private hidden=false;private prepared='';private preparing='';private solo=false;private starting=false;private frames=0;private id=0;private uiKey='';private playerName='准点员工';private code='';private gender='male';private job='programmer';private role='coder';private note='';private material!:Material;private failed=false;private lastAction:any=null;private diagnosticTime=0;private diagnostic:HTMLElement|null=null;
 start(){
  if(sys.isBrowser&&typeof location!=='undefined'&&new URLSearchParams(location.search).get('profile')==='on')profiler.showStats();else profiler.hideStats();
  this.camera=this.node.getChildByName('Main Camera')!;this.coastalSky=new EngineCoastalSky(this.camera.getComponent(Camera)!);void this.coastalSky.prepare();if(!this.environment||!this.character)throw Error('Office/character prefab missing');
  const office=instantiate(this.environment);this.node.addChild(office);this.office=office;this.materialAlpha.apply(office,'headquarters');this.prefabs.set('male_programmer',this.character);this.material=new Material();this.material.initialize({effectName:'builtin-unlit'});this.material.setProperty('mainColor',new Color(255,129,77));
  this.arms=new EngineFirstPerson(this.camera,this.prefabs,(node,slot)=>this.configureCharacterMaterials(node,slot));this.weapons=new EngineWeapons(this.node,this.camera);this.ui=new EngineUi(this.node);this.sound=new EngineAudio(this.node);
  this.session=new GameSession({openSocket:()=>new WebSocket(this.serverUrl),requestId:()=>`engine-${Date.now()}-${this.id++}-${Math.random().toString(16).slice(2)}`,onChange:()=>this.changed(),onMessage:(text:string)=>{this.note=text;},onEvent:(event:any)=>{this.sound.event(event);this.weapons.event(event);if(event.text)this.note=event.text;}});
  (globalThis as any).corporateEngineDiagnostics=()=>({frames:this.frames,connected:this.session.connected,playerId:this.session.playerId,state:this.session.state,prepared:this.prepared,actors:Array.from(this.actors.entries()).map(([id,a])=>({id,slot:a.slot,action:a.action})),pose:this.session.prediction.pose,camera:this.camera.position,menu:this.menu,note:this.note});
  input.on(Input.EventType.KEY_DOWN,this.keyDown,this);input.on(Input.EventType.KEY_UP,this.keyUp,this);input.on(Input.EventType.MOUSE_MOVE,this.look,this);input.on(Input.EventType.MOUSE_DOWN,this.mouseDown,this);input.on(Input.EventType.MOUSE_UP,this.mouseUp,this);game.on(Game.EVENT_HIDE,this.hide,this);game.on(Game.EVENT_SHOW,this.show,this);
  if(sys.isBrowser&&typeof document!=='undefined'){this.diagnostic=document.createElement('output');this.diagnostic.id='engine-runtime-evidence';this.diagnostic.hidden=true;document.body.appendChild(this.diagnostic);}
  this.makeControls();this.changed();this.session.connect();this.inputTimer=setInterval(()=>{this.session.tick();this.sendInput();},1000/INPUT_HZ);
 }
 private load(slot:string):Promise<Prefab>{
  if(this.prefabs.has(slot))return Promise.resolve(this.prefabs.get(slot)!);if(this.loads.has(slot))return this.loads.get(slot)!;
  const name=slot==='male_programmer'?'programmer':slot,first=slot.startsWith('fp_'),actionSlot=first?slot.slice(3):slot;
  const promise=new Promise<Prefab>((resolve,reject)=>resources.load(`${name}/${name}`,Prefab,(error,prefab)=>{
   if(error){this.loads.delete(slot);reject(error);return;}
   const instance=instantiate(prefab);const animation=instance.getComponent(SkeletalAnimation)??instance.getComponentInChildren(SkeletalAnimation);const complete=[...ANIMATION_NAMES,...WEAPON_ANIMATION_NAMES,...(first?[]:['Talk'])].every(name=>animation?.clips.some(c=>c?.name===`${actionSlot}_${name}`));instance.destroy();if(!complete){this.loads.delete(slot);reject(Error(`动作资源缺失：${slot}`));return;}this.prefabs.set(slot,prefab);resolve(prefab);
  }));this.loads.set(slot,promise);return promise;
 }
 private changed(){
  const s:any=this.session?.state;if(this.dialogueNpc&&(!this.session.connected||this.focus.observe(s,this.session.playerId,performance.now())))this.endDialogue();const key=s?`${s.id}:${s.loadoutRevision}`:'';
  if(key&&key!==this.prepared&&key!==this.preparing){this.preparing=key;this.failed=false;const slots=Array.from(new Set<string>([...s.players,...(s.npcs??[])].map((p:any)=>characterAssetSlot(p))));slots.push('male_sales');const local=s.players.find((p:any)=>p.id===this.session.playerId);if(local)slots.push('fp_'+characterAssetSlot(local));
   Promise.all([...slots.map(slot=>this.load(slot)),this.sound.prepare()]).then(()=>{if(!this.isValid||this.preparing!==key||`${this.session.state?.id}:${this.session.state?.loadoutRevision}`!==key)return;this.prepared=key;this.preparing='';this.uiKey='';if(this.solo&&this.session.state?.status==='lobby'){this.solo=false;this.session.ready();this.session.command({type:'start'});}this.changed();}).catch(error=>{if(this.preparing!==key)return;this.note=String(error);this.failed=true;this.uiKey='';this.drawUi();});
  }
  if(!s){this.sound.stop();this.prepared='';this.preparing='';this.clearActors();this.camera.setPosition(-18,1.65,5.8);this.yaw=0;this.pitch=0;}
  this.drawUi();
 }
 private drawUi(){
  const s:any=this.session?.state;const me=s?.players.find((p:any)=>p.id===this.session.playerId);const ready=s&&this.prepared===`${s.id}:${s.loadoutRevision}`;
  const key=`${this.dialogueNpc}:${s?.story?.dialogue?.topicId??''}:${s?.status??'home'}:${s?.id??''}:${s?.loadoutRevision??0}:${s?.players.map((p:any)=>p.ready).join(',')??''}:${ready}:${this.menu}:${this.session?.connected}:${this.failed}:${this.soundSettings}:${this.starting}`;this.ui.panel.active=this.soundSettings||!s||s.status!=='running'||this.menu;this.ui.controls.active=s?.status==='running'&&!this.menu&&!this.soundSettings;this.ui.setConversation(Boolean(this.dialogueNpc));this.controls.setActive(Boolean(this.session?.connected&&s?.status==='running'&&!this.menu&&!this.soundSettings&&!this.hidden));
  if(key!==this.uiKey){this.uiKey=key;this.ui.clearPanel();const p=this.ui.panel;
   if(this.dialogueNpc&&s){const npc=s.npcs.find((n:any)=>n.id===this.dialogueNpc);this.ui.text(p,npc.name+' · '+npc.profession,0,240,500,55,26);this.ui.text(p,s.story.dialogue?.npcId===npc.id?s.story.dialogue.text:'正在'+(npc.activity??npc.habit)+'，愿意和你聊聊。',0,110,500,140,20);npc.topics.forEach((topic:any,i:number)=>{this.ui.button(p,topic.label,0,-20-i*65,()=>this.session.command({type:'dialogue',npcId:npc.id,topicId:topic.id}),500).interactable=storyTopicAvailable(s.story,topic);});this.ui.button(p,'结束交谈',0,-240,()=>this.endDialogue());}else if(this.soundSettings){this.drawSoundSettings(p);}else if(!s){this.ui.text(p,'准时下班 · 海岸总部',0,250,650,55,28);const field=this.ui.field(p,'员工代号',0,170,this.playerName);field.node.on('editing-did-ended',()=>this.playerName=field.string);
    this.ui.button(p,this.gender==='male'?'人物：男生':'人物：女生',-150,95,()=>{this.gender=this.gender==='male'?'female':'male';this.uiKey='';this.drawUi();});
    this.ui.button(p,'服装：'+{programmer:'程序员',ecommerce:'电商',sales:'销售',celebrity:'明星'}[this.job],150,95,()=>{const jobs=['programmer','ecommerce','sales','celebrity'];this.job=jobs[(jobs.indexOf(this.job)+1)%4];this.uiKey='';this.drawUi();});
    this.ui.button(p,this.role==='coder'?'技能：研发干扰':'技能：行政冲撞',0,25,()=>{this.role=this.role==='coder'?'admin':'coder';this.uiKey='';this.drawUi();});
    const create=()=>this.startSingle(field.string);
    this.ui.button(p,this.starting?'正在准备…':'单人出发',-150,-65,create).interactable=this.session.connected&&!this.starting;
    if(this.starting)this.ui.text(p,'准备职业人物与声音资源，完成后进入办公室。',0,-130,650,45,18);
    
    this.ui.text(p,'WASD 移动 · 按住右键环视\nE 交接 / 救援 / 撤离 · J 攻击 · K 技能\nF 拾取 · R 装填 · B 切换武器 · 空格闪避 · L 投掷 · ESC 菜单',0,-225,650,120,18);
   }else if(s.status==='lobby'){
    this.ui.text(p,'合作房间 '+s.id,0,250,650,55,28);this.ui.text(p,s.players.map((p:any)=>`${p.name} · ${p.gender==='male'?'男':'女'} / ${p.job} · ${p.ready?'已准备':'等待'}`).join('\n'),0,110,650,180,21);
    this.ui.text(p,ready?'本房间人物已加载':this.failed?'资源失败，请重试':'正在准备本房间服装…',0,-20,650,50,18);
    this.ui.button(p,this.failed?'重新加载':'准备',-150,-95,()=>{if(this.failed){this.preparing='';this.changed();}else this.session.ready();}).interactable=this.failed||Boolean(ready&&!me.ready);
    this.ui.button(p,'全员出发',150,-95,()=>this.session.command({type:'start'})).interactable=ready&&s.host===this.session.playerId&&s.players.every((p:any)=>p.ready);
    this.ui.button(p,'返回大厅',0,-180,()=>this.leave());
   }else if(s.status==='ended'){
    const ending=s.result.storyEnding;this.ui.text(p,ending?.title??(s.result.success?'下班行动完成':'行动结束'),0,220,650,70,28);this.ui.text(p,ending?ending.summary+'\n\n'+ending.voices.map((v:any)=>v.name+'：'+v.text).join('\n'):me.state==='extracted'?'你已准时下班。':'本次未能撤离。',0,35,620,260,20);if(ending)this.ui.text(p,'核对证据 '+ending.evidence.length+'/3 · '+(ending.selfCare?'给自己留了休息':'这次未选择休息'),0,-145,620,45,18);this.ui.button(p,'返回大厅',0,-225,()=>this.leave());
   }else{this.ui.text(p,'行动菜单',0,180,650,70,30);this.ui.text(p,'返回大厅将退出本次行动。',0,60,650,70,20);this.ui.button(p,'继续行动',0,-40,()=>{this.menu=false;this.drawUi();});this.ui.button(p,'退出 · 返回大厅',0,-115,()=>this.leave());}
  }
  this.ui.notice.string=this.sound.caption||this.note|| (this.session.connected?'服务已连接':'正在重连服务…');
  const nearby=me&&nearestStoryNpc(s,me);
  this.ui.hud.string=s?.status==='running'?`${s.story?.deadline===null?'自由探索':Math.ceil(s.remaining)+' 秒'} · ${Math.ceil(me.hp)} 生命 · ${weaponLabel(me,s.elapsed)??me.weapon??'空手'} · 能量 ${Math.floor(me.energy)}%\n${s.story?.phase==='explore'?[['schedule','原始日程'],['policy','公司制度'],['ledger','审批记录']].map(([id,label])=>`${s.story.clues.includes(id)?'✓':'○'} ${label}`).join('   '):s.objectives.map((o:any)=>`${o.done?'✓':'○'} ${o.label}`).join('   ')}   ${s.exitOpen?'电梯已开放':s.story?.phase==='explore'?'交谈收集线索，选择协商或质询':'击败组长后撤离'}${me.interactProgress?` · 互动 ${me.interactProgress.toFixed(1)}s`:''}${nearby?'\n附近：'+nearby.name+' · '+nearby.activity+'（T 交谈）':''}`:'';
 }
 private startSingle(name:string){if(this.starting||this.session.state||!this.session.connected)return;this.playerName=name;const request={type:'create',mode:'single',name,role:this.role,gender:this.gender,job:this.job};this.starting=true;this.note='正在准备人物资源…';this.uiKey='';this.drawUi();const slots=Array.from(new Set<string>([`${this.gender}_${this.job}`,...STORY_NPCS.map(n=>characterAssetSlot(n)),'male_sales']));Promise.all([...slots.map(slot=>this.load(slot)),this.sound.prepare()]).then(()=>{if(!this.isValid)return;this.starting=false;if(this.session.state)return;this.solo=true;if(!this.session.send(request)){this.solo=false;this.note='服务连接已中断，请重新出发。';}this.uiKey='';this.drawUi();}).catch(error=>{if(!this.isValid)return;this.starting=false;this.note='人物准备失败：'+String(error);this.uiKey='';this.drawUi();});}
 private leave(){this.focus.end();this.controls.setActive(false);this.sound.stop();this.note='';this.soundSettings=false;this.dialogueNpc='';this.menu=false;this.solo=false;this.held.clear();this.session.leave();}
 private drawSoundSettings(p:Node){
  this.ui.text(p,this.session.state?.status==='running'?'声音设置':'声音设置',0,255,650,50,26);
  const refresh=()=>{this.uiKey='';this.drawUi();};
  this.ui.button(p,this.sound.settings.enabled?'声音：开':'声音：关',-150,195,()=>{this.sound.configure({enabled:!this.sound.settings.enabled});refresh();});
  this.ui.button(p,this.sound.settings.captions?'字幕：开':'字幕：关',150,195,()=>{this.sound.configure({captions:!this.sound.settings.captions});refresh();});
  for(const [i,key,label]of [[0,'master','总音量'],[1,'music','下班节拍'],[2,'effects','脚步与动作'],[3,'alerts','危险提示'],[4,'ambient','办公室环境'],[5,'voice','广播提示音']] as const){const y=130-i*49;this.ui.text(p,label+'  '+Math.round(this.sound.settings[key]*100)+'%',0,y,390,42,20);for(const [x,delta]of [[-260,-.1],[260,.1]])this.ui.button(p,delta<0?'−':'+',x,y,()=>{this.sound.configure({[key]:this.sound.settings[key]+delta});refresh();},80);}
  this.ui.text(p,this.sound.status+' · 广播文字以字幕显示',0,-195,650,40,16);this.ui.button(p,'返回',0,-250,()=>{this.soundSettings=false;refresh();});
 }
 private endDialogue(){const active=Boolean(this.dialogueNpc);this.focus.end();this.dialogueNpc='';this.menu=false;this.held.clear();this.controls.setActive(false);if(active&&this.session.connected&&this.session.state?.status==='running')this.session.command({type:'conversation',active:false});this.uiKey='';this.drawUi();this.sendInput();}
 private openDialogue(){const s:any=this.session.state;if(!this.session.connected||s?.status!=='running'||this.menu||this.soundSettings||this.dialogueNpc)return;const me=s.players.find((p:any)=>p.id===this.session.playerId),npc=me?.state==='active'&&nearestStoryNpc(s,me);if(!npc){this.note='靠近人物后再交谈';return;}if(!this.session.command({type:'conversation',npcId:npc.id,active:true}))return;this.focus.begin(s.id,npc.id,performance.now());this.dialogueNpc=npc.id;this.menu=true;this.held.clear();this.controls.setActive(false);this.uiKey='';this.drawUi();this.sendInput();}
 private makeControls(){
  this.ui.button(this.ui.navigation,'交谈 T',-440,315,()=>this.openDialogue(),130);
  this.ui.button(this.ui.navigation,'切换视角 V',300,315,()=>{this.thirdPerson=!this.thirdPerson;},150);
  this.ui.button(this.ui.navigation,'声音',440,315,()=>{this.soundSettings=true;if(this.session.state?.status==='running')this.menu=true;this.held.clear();this.uiKey='';this.drawUi();this.sendInput();},100);
  const p=this.ui.controls;this.ui.button(p,'拾取 F',-200,315,()=>{this.controls.press('pickup');this.controls.release('pickup');},130);this.ui.text(p,'+',0,0,40,40,28);
  const hold=(label:string,x:number,y:number,action:string)=>{const button=this.ui.button(p,label,x,y,()=>{},110);button.node.on(Node.EventType.TOUCH_START,()=>this.controls.press(action,'touch'));button.node.on(Node.EventType.TOUCH_END,()=>this.controls.release(action,{source:'touch'}));button.node.on(Node.EventType.TOUCH_CANCEL,()=>this.controls.release(action,{cancel:true,source:'touch'}));};
  hold('前',-500,-190,'forward');hold('后',-500,-285,'back');hold('左',-600,-240,'left');hold('右',-400,-240,'right');
  for(const [i,label,action]of [[0,'攻击','attack'],[1,'技能','skill'],[2,'互动','interact'],[3,'装填','reload'],[4,'闪避','dodge'],[5,'投掷','throw'],[6,'变身','transform'],[7,'切换武器','weaponNext']] as const)hold(label,100+(i%4)*130,-210-Math.floor(i/4)*65,action);
  this.ui.button(p,'菜单',560,315,()=>{this.menu=true;this.held.clear();this.drawUi();this.sendInput();},110);
  const look=this.ui.text(p,'拖动环视',350,-50,430,230,14);look.node.on(Node.EventType.TOUCH_MOVE,(e:EventTouch)=>{const d=e.getDelta();this.turn(d.x,d.y);});
 }
 private turn(x:number,y:number){if(this.menu||this.soundSettings||this.hidden||this.session.state?.status!=='running')return;this.yaw-=x*.16;this.pitch=Math.max(-75,Math.min(75,this.pitch+y*.16));}
 private keyAction(code:KeyCode){return new Map<KeyCode,string>([[KeyCode.KEY_W,'forward'],[KeyCode.KEY_S,'back'],[KeyCode.KEY_A,'left'],[KeyCode.KEY_D,'right'],[KeyCode.KEY_J,'attack'],[KeyCode.KEY_K,'skill'],[KeyCode.KEY_E,'interact'],[KeyCode.SPACE,'dodge'],[KeyCode.KEY_L,'throw'],[KeyCode.KEY_Q,'transform'],[KeyCode.KEY_R,'reload'],[KeyCode.KEY_B,'weaponNext'],[KeyCode.KEY_F,'pickup']]).get(code);}
 private keyDown(event:EventKeyboard){if(event.keyCode===KeyCode.KEY_T){this.openDialogue();return;}if(event.keyCode===KeyCode.KEY_V){if(this.dialogueNpc)return;this.thirdPerson=!this.thirdPerson;return;}if(event.keyCode===KeyCode.ESCAPE){if(this.escapeHeld)return;this.escapeHeld=true;if(this.dialogueNpc){this.endDialogue();}else if(this.soundSettings){this.soundSettings=false;this.uiKey='';}else if(this.session.state?.status==='running')this.menu=!this.menu;this.held.clear();this.drawUi();this.sendInput();return;}const action=this.keyAction(event.keyCode);if(action)this.controls.press(action);}
 private keyUp(event:EventKeyboard){if(event.keyCode===KeyCode.ESCAPE)this.escapeHeld=false;const action=this.keyAction(event.keyCode);if(action)this.controls.release(action);}
 private mouseDown(event:EventMouse){if(event.getButton()===2)this.held.add('look');}
 private mouseUp(event:EventMouse){if(event.getButton()===2)this.held.delete('look');}
 private look(event:EventMouse){if(this.held.has('look')){const d=event.getDelta();this.turn(d.x,d.y);}}
 private hide(){this.escapeHeld=false;this.held.clear();this.hidden=true;this.controls.setActive(false);this.sendInput(true);this.sound.setHidden(true);}
 private show(){this.hidden=false;this.sound.setHidden(false);this.drawUi();}
 private sendInput(force=false){if((force||!this.hidden)&&this.session.state?.status==='running'){const intent={...this.controls.next(this.yaw),pitch:Math.max(-1.15,Math.min(1.15,this.pitch*Math.PI/180)),thirdPerson:this.thirdPerson,cancelActions:!this.controls.active};if(Object.entries(intent).some(([k,v])=>['pickup','attack','reload','weaponNext'].includes(k)&&v===true))this.lastAction={...intent,sequence:this.session.sequence};this.session.input(intent);}}
 update(dt:number){
  this.frames++;if(this.office&&!this.environmentBatching){const mode=sys.isBrowser&&typeof location!=='undefined'?new URLSearchParams(location.search).get('batch'):null;this.environmentBatching=mode==='static'||mode==='off'?new EnvironmentBatching(this.office,mode!=='off'):new EnvironmentInstancing(this.office);}const s:any=this.session.state;if(this.dialogueNpc&&(!this.session.connected||this.focus.observe(s,this.session.playerId,performance.now())))this.endDialogue();this.sound.tick(s,s?.players.find((p:any)=>p.id===this.session.playerId));this.ui.notice.string=this.sound.caption||this.note||(this.session.connected?'服务已连接':'正在重连服务…');this.diagnosticTime+=dt;if(this.diagnostic&&this.diagnosticTime>=.5){this.diagnosticTime=0;const me=s?.players.find((p:any)=>p.id===this.session.playerId);Object.assign(this.diagnostic.dataset,{audio:JSON.stringify(this.sound.diagnostics()),performance:JSON.stringify(profiler.isShowingStats()?{fps:profiler.stats?.fps.counter?.human(),draws:profiler.stats?.draws.counter?.human(),triangles:profiler.stats?.tricount.counter?.human(),textureMiB:profiler.stats?.textureMemory.counter?.human(),bufferMiB:profiler.stats?.bufferMemory.counter?.human()}:null),batching:JSON.stringify(this.environmentBatching?.report??null),materialAlpha:JSON.stringify(this.materialAlpha.report),coastalSky:JSON.stringify(this.coastalSky.report),cameraDistance:String(this.cameraDistance),localAvatarVisible:String(this.thirdPerson&&!this.dialogueNpc&&this.avatarVisible),cameraMode:this.dialogueNpc?'conversation':this.thirdPerson?'third':'first',gameplayAim:JSON.stringify({yaw:this.yaw,pitch:this.pitch,thirdPerson:this.thirdPerson}),dialogueNpc:this.dialogueNpc,firstPersonArms:JSON.stringify(this.arms?.diagnostics()??null),weaponAttachments:JSON.stringify(this.weapons?.diagnostics()??[]),actorStates:JSON.stringify(Array.from(this.actors,([id,a])=>({id,slot:a.slot,action:a.action,visible:a.node.activeInHierarchy,lensAlpha:a.lensAlpha}))),input:JSON.stringify({active:this.controls.active,sequence:this.session.sequence,hidden:this.hidden,soundSettings:this.soundSettings,lastAction:this.lastAction}),frames:String(this.frames),connected:String(this.session.connected),status:s?.status??'home',story:JSON.stringify(s?.story??null),result:JSON.stringify(s?.result??null),room:s?.id??'',x:String(me?.x??''),z:String(me?.z??''),actors:String(this.actors.size),npcs:JSON.stringify((s?.npcs??[]).map((n:any)=>({id:n.id,x:n.x,z:n.z,behavior:n.behavior,activity:n.activity,visits:n.visits,conversing:n.conversing}))),menu:String(this.menu),weapon:weaponLabel(me??{},s?.elapsed),inventory:JSON.stringify(me?.inventory??[]),note:this.note});}if(!s)return;const me=s.players.find((p:any)=>p.id===this.session.playerId);if(!me)return;
  const pose:any=this.session.prediction.pose??me,npc=this.dialogueNpc?s.npcs?.find((n:any)=>n.id===this.dialogueNpc):null;const facing=npc?conversationFacing(pose,npc,{ground:floorHeight(pose.x,pose.z),targetGround:floorHeight(npc.x,npc.z),fallbackYaw:this.yaw*Math.PI/180}):{yaw:this.yaw*Math.PI/180,pitch:this.pitch*Math.PI/180};const orbit=cameraPose({x:pose.x,z:pose.z,ground:floorHeight(pose.x,pose.z),yaw:facing.yaw,pitch:facing.pitch,thirdPerson:npc?false:this.thirdPerson,down:me.state==='down',walls:WALLS});this.cameraDistance=orbit.distance;this.avatarVisible=cameraAvatarVisible(orbit.distance,this.avatarVisible);this.camera.setPosition(orbit.x,orbit.y,orbit.z);this.camera.setRotationFromEuler(facing.pitch*180/Math.PI,facing.yaw*180/Math.PI,0);
  this.renderActors(s,dt);this.renderProps(s);const firstPerson=this.arms.sync(me,characterAssetSlot(me),s.elapsed,s.status==='running'&&me.state==='active'&&!this.dialogueNpc&&!this.thirdPerson,dt,pose);this.weapons.sync(s,this.session.playerId,Boolean(this.dialogueNpc)||this.thirdPerson,this.actors,firstPerson);this.drawUi();
 }
 private configureCharacterMaterials(node:Node,slot:string){this.materialAlpha.apply(node,slot);let lensAlpha:number|null=null;for(const renderer of node.getComponentsInChildren(MeshRenderer))for(const material of renderer.sharedMaterials)if(material?.name==='Teacher_Clear_Lenses'){const color=material.getProperty('mainColor') as Color|undefined;lensAlpha=color?color.a/255:null;}return lensAlpha;}
 private renderActors(s:any,dt:number){
  const entities=this.session.interpolation.entities(performance.now());const keep=new Set<string>();
  for(const original of [...s.players,...s.enemies,...(s.npcs??[])]){if(original.id===this.session.playerId&&s.status==='running'&&(!this.thirdPerson||Boolean(this.dialogueNpc)))continue;keep.add(original.id);const e:any=entities.get(original.id)??original;const slot=e.gender?characterAssetSlot(e):e.kind==='boss'?'male_sales':'male_programmer';const prefab=this.prefabs.get(slot);if(!prefab)continue;let actor=this.actors.get(e.id);
   if(actor?.slot!==slot){actor?.node.destroy();this.actors.delete(e.id);actor=undefined;}if(!actor){const node=instantiate(prefab);this.node.addChild(node);const animation=node.getComponent(SkeletalAnimation)??node.getComponentInChildren(SkeletalAnimation);if(!animation)continue;actor={node,animation,slot,action:'',marker:null,position:new Vec3(e.x,0,e.z),hp:e.hp,hitUntil:0,lensAlpha:this.configureCharacterMaterials(node,slot)};this.actors.set(e.id,actor);}
   const speed=Math.hypot(e.x-actor.position.x,e.z-actor.position.z)/Math.max(dt,.001);if(e.hp<actor.hp)actor.hitUntil=s.elapsed+.2;actor.hp=e.hp;actor.position.set(e.x,0,e.z);actor.node.setPosition(e.x,floorHeight(e.x,e.z),e.z);actor.node.setRotationFromEuler(0,Math.atan2(e.fx??0,e.fz??1)*180/Math.PI,0);
   const name=selectAnimation({...e,player:Boolean(e.gender)},s.elapsed,speed,{talkAvailable:true,weaponAvailable:true,lobby:s.status==='lobby',hitActive:s.elapsed<actor.hitUntil,rescueTargets:new Set(s.players.filter((p:any)=>p.state==='down').map((p:any)=>p.id))});const marker=(name==='Attack'||name.endsWith('Shot'))?e.attackUntil:name==='Cast'?e.cast?.end:name==='Hit'?actor.hitUntil:null;
   actor.node.active=!['extracted','left'].includes(e.state)&&(e.id!==this.session.playerId||s.status!=='running'||this.avatarVisible);
   if(actor.action!==name||actor.marker!==marker){actor.animation.crossFade(`${slot}_${name}`,.1);const state=actor.animation.getState(`${slot}_${name}`);if(state){state.wrapMode=['Idle','Walk','Run','Rescue','Talk',...WEAPON_ANIMATION_NAMES.filter(n=>!n.endsWith('Shot'))].includes(name)?AnimationClip.WrapMode.Loop:AnimationClip.WrapMode.Normal;if(name==='Attack'||name.endsWith('Shot'))state.speed=state.duration/.22;if(name==='Hit')state.speed=state.duration/.2;}actor.action=name;actor.marker=marker;}
  }
  for(const [id,a]of this.actors)if(!keep.has(id)){a.node.destroy();this.actors.delete(id);}
 }
 private renderProps(s:any){const keep=new Set<string>();const mark=(id:string,x:number,z:number,r:number)=>{keep.add(id);let n=this.props.get(id);if(!n){n=new Node(id);const renderer=n.addComponent(MeshRenderer);renderer.mesh=utils.createMesh(primitives.torus(1,.04,{radialSegments:8,tubularSegments:28}));renderer.setMaterial(this.material,0);this.node.addChild(n);this.props.set(id,n);}n.setScale(r,1,r);n.setPosition(x,floorHeight(x,z)+.05,z);};
  if(s.status==='running'){for(const o of s.objectives)if(!o.done)mark('交接 '+o.id,o.x,o.z,.5);for(const e of s.enemies){mark('敌人 '+e.id,e.x,e.z,e.kind==='boss'?.6:.35);if(e.cast)mark('危险 '+e.id,e.cast.x,e.cast.z,e.cast.radius);}if(s.exitOpen)mark('撤离',LEVEL.exit.x,LEVEL.exit.z,.7);for(const i of s.items)mark('道具 '+i.id,i.x,i.z,.2);for(const p of s.projectiles)mark('文件 '+p.id,p.x,p.z,.15);}
  for(const [id,n]of this.props)if(!keep.has(id)){n.getComponent(MeshRenderer)?.mesh?.destroy();n.destroy();this.props.delete(id);}
 }
 private clearActors(){this.weapons?.clear();this.arms?.clear();for(const a of this.actors.values())a.node.destroy();this.actors.clear();for(const n of this.props.values()){n.getComponent(MeshRenderer)?.mesh?.destroy();n.destroy();}this.props.clear();}
 onDestroy(){if(this.inputTimer!==null)clearInterval(this.inputTimer);this.controls.setActive(false);this.sound?.dispose();this.weapons?.dispose();this.environmentBatching?.dispose();this.diagnostic?.remove();this.session?.dispose();this.clearActors();this.coastalSky?.dispose();this.materialAlpha.dispose();this.material?.destroy();input.off(Input.EventType.KEY_DOWN,this.keyDown,this);input.off(Input.EventType.KEY_UP,this.keyUp,this);input.off(Input.EventType.MOUSE_MOVE,this.look,this);input.off(Input.EventType.MOUSE_DOWN,this.mouseDown,this);input.off(Input.EventType.MOUSE_UP,this.mouseUp,this);game.off(Game.EVENT_HIDE,this.hide,this);game.off(Game.EVENT_SHOW,this.show,this);delete (globalThis as any).corporateEngineDiagnostics;}
}
